// Modified for Distill by Samuel Fajreldines, 2026.
//! Ultracode concern for `SessionActor`: per-turn orchestration reminder while the session flag is on.
use super::*;

pub(super) const ULTRACODE_DIRECTIVE: &str = "Ultracode mode is ON. Choose the smallest useful action: investigate concrete uncertainty or decompose only into independently verifiable smaller tasks. Preserve a suitable configured execution owner, considering available capability, relative cost and handoff overhead; if that information is unavailable, follow applicable defaults without assuming savings. Execute directly when assigned the slice or delegation is unavailable or adds no value; avoid re-delegating owned work. Keep inspection, implementation and check execution with configured execution owner. For nontrivial cross-interface work without independent acceptance proof, ask a fresh existing read-only plan subagent to design a small runnable check with fixed expectations before proposed code/tests/results exist; wait for its returned check before implementation edits. Give original contract and existing entrypoints; do not resume/fork implementation context for planner check design. Planner returns text/code only, cannot edit/execute; existing availability/admission fallback governs. Other exploration/planning needs concrete uncertainty. No agent quota. Preserve useful independent parallel work and quality checks. Before delegating, state the objective, restrictions, owned paths, acceptance criteria and existing evidence references. Preserve the exact relevant acceptance contract in execution and verification handoffs. Write ownership does not bound verification: trace the full user-visible path through actual entrypoints and unchanged callers/adapters within read grants. Reuse adequate independent proof; keep mechanical work lightweight. Authorized configured execution owner runs the check with existing tools before edits, records baseline and fixed expected outcome, reruns after integration. Carry each discriminating case's same values/fixed contract expectation through that path in applicable boundary representations at validation/data-preservation boundaries; lower-layer passes plus simpler entrypoint cases do not suffice. Never fit expectations to code; report uncovered requirements and test/execution limits. Preserve explicit model/effort pins and capability and permission ceilings. Delegate only tasks smaller than the parent objective, within the shared depth, concurrency and budget limits. If admission is refused, execute locally or wait for independent work to finish; never recursively retry or multiply budgets. Workflow-owned, harness-internal, output-budgeted and isolated-worktree agents are leaves. Integrate child results by inspecting their evidence and actual changes, then verify the parent objective; a child report alone is not completion. Report unresolved uncertainty and concrete runtime limits.";

impl SessionActor {
    /// Called once per user turn from `handle_prompt()`; pushes nothing while Ultracode is off.
    pub(super) fn inject_ultracode_reminder(&self) {
        if self.ultracode.load(std::sync::atomic::Ordering::Relaxed) {
            self.push_system_reminder_with_tag(ULTRACODE_DIRECTIVE, self.reminder_wrapper_tag());
        }
    }
}
