#!/usr/bin/env python3
# Modified for Distill by Samuel Fajreldines, 2026.
"""Turn the owner's cat script into the asset the welcome screen draws.

`gatinho_sem_balao.sh` paints a truecolor half-block picture: every terminal cell
is one `▀` whose foreground is the top pixel and whose background is the bottom
one. The TUI cannot run a shell script, so this reads that stream once and writes
`assets/logo/cat-px.txt`: one line per cell row, one 12-hex-digit cell per
column (`RRGGBB` foreground then `RRGGBB` background).

Usage: python3 tools/cat-art.py [source.sh] [out.txt]
"""

import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
LOGO_DIR = REPO / "crates" / "codegen" / "distill-pager" / "assets" / "logo"
DEFAULT_SOURCE = LOGO_DIR / "cat-source.sh"
DEFAULT_OUT = LOGO_DIR / "cat-px.txt"

# One cell: foreground SGR, background SGR, then the half block.
PAIR = re.compile(r"38;2;(\d+);(\d+);(\d+)m\S*?48;2;(\d+);(\d+);(\d+)m")


def cells_from(line: str) -> list[tuple[tuple[int, ...], tuple[int, ...]]]:
    found = PAIR.findall(line)
    return [
        ((int(fg[0]), int(fg[1]), int(fg[2])), (int(bg[0]), int(bg[1]), int(bg[2])))
        for fg, bg in ((m[:3], m[3:]) for m in found)
    ]


def main() -> int:
    source = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_SOURCE
    out = pathlib.Path(sys.argv[2]) if len(sys.argv) > 2 else DEFAULT_OUT

    rows = [cells for cells in map(cells_from, source.read_text().splitlines()) if cells]
    if not rows:
        print(f"no painted rows in {source}", file=sys.stderr)
        return 1
    widths = {len(row) for row in rows}
    if len(widths) != 1:
        print(f"ragged art: widths {sorted(widths)}", file=sys.stderr)
        return 1

    lines = [
        "# The Distill cat, as the owner's script paints it.",
        f"# Generated by tools/cat-art.py from {source.name} — edit that, not this.",
        "# One line per cell row; each cell is 12 hex digits: top pixel then bottom.",
    ]
    for row in rows:
        lines.append(
            "".join(
                f"{top[0]:02x}{top[1]:02x}{top[2]:02x}{bottom[0]:02x}{bottom[1]:02x}{bottom[2]:02x}"
                for top, bottom in row
            )
        )
    out.write_text("\n".join(lines) + "\n")
    print(f"{out.relative_to(REPO)}: {len(rows)} rows x {rows[0].__len__()} cells")
    return 0


if __name__ == "__main__":
    sys.exit(main())
